name: 'Remove old Releases'
on:
  push:
  schedule:
    - cron: 0 23 * * *
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
            keep_latest: 30
            delete_tags: true
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


